name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-python.yml@ea195638c4c96f1d94aa7628a233a739e3d068cf # v4.1.1
    with:
      python-versions: '["3.11","3.12","3.13","3.14"]'
