name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-python.yml@ebf1be0e9a042e490eef4062613562225d4d206f # v5.0.0
    with:
      python-versions: '["3.11","3.12","3.13","3.14"]'
