name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-python.yml@2999ae87b709bd1b1bb9ab110aa3055828848898 # v6.0.0
    with:
      python-versions: '["3.11","3.12","3.13","3.14"]'
