name: 'Dependency review'
on:
  pull_request:
    branches: [ "main" ]

permissions: {}

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write  # to comment review summary
    uses: iwamot/workflows/.github/workflows/dependency-review.yml@8a5a298fe570b32a00513bdbacddadb8fd1c0cfc # v3.0.0
