name: Dependabot auto-merge
on: pull_request

permissions: {}

jobs:
  dependabot-auto-merge:
    permissions:
      contents: write       # to merge auto-merge PRs
      pull-requests: write  # to enable auto-merge
    uses: iwamot/workflows/.github/workflows/dependabot-auto-merge.yml@8a5a298fe570b32a00513bdbacddadb8fd1c0cfc # v3.0.0
