name: oide

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/oide.yml

permissions: {}

jobs:
  pull:
    permissions:
      contents: write       # to push the branch
      pull-requests: write  # to open the PR
    uses: iwamot/workflows/.github/workflows/oide.yml@8a5a298fe570b32a00513bdbacddadb8fd1c0cfc # v3.0.0
