name: Validate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
      id-token: write  # for Codecov OIDC upload
    uses: iwamot/workflows/.github/workflows/validate-with-coverage.yml@8a5a298fe570b32a00513bdbacddadb8fd1c0cfc # v3.0.0
